name: .NET MAUI Android Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List repository files (debugging)
      run: dir /s /b

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore EventPlannerApp/EventPlannerApp.sln

    - name: Build .NET MAUI Android project
      run: dotnet build EventPlannerApp/EventPlannerApp.sln -f net8.0-android -c Release

    - name: Run unit tests
      run: dotnet test UnitTestEventPlanner/UnitTestEventPlanner.csproj -c Release
